services:
  - type: redis
    name: dler-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic

  - type: worker
    name: dler-worker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: celery -A app.celery worker --loglevel=info
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic
    envVars:
      - key: REDIS_URL
        fromService:
          name: dler-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: dler-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic
    envVars:
      - key: REDIS_URL
        fromService:
          name: dler-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /docs
